version: '3'
services:
    postgres:
      image: postgres:latest
      container_name: postgres_dc
      environment:
        POSTGRES_USER: root
        POSTGRES_DB: dev
        POSTGRES_PASSWORD: 123456
      ports:
        - "5432:5432"

